name: flutter_nfc_reader
description: NFC gate app.
version: 0.0.23
author: Wojciech Tomasiewicz

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: '>= 0.9.3-pre'

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter


flutter:
  plugin:
    androidPackage: it.matteocrippa.flutternfcreader
    pluginClass: FlutterNfcReaderPlugin
